### ISSUE TITLE
Does AWS UI meet accessibilty standards?

### ISSUE THREAD

**Issue by nguyen102** [aws/awsui-documentation#23]
Hi, 

I would like to ask if AWS UI components meet [WCAG](https://www.w3.org/WAI/WCAG21/Understanding/conformance#levels) accessibility standards? This will affect whether we can use the components in our future projects.

Thanks,
Tim

**Comment by just-boris** [comment]
Hello!

Our library follows general AWS standards.

Please refer to our online website regarding [AWS Section 508 Compliance](https://aws.amazon.com/compliance/vpat/) for more information about how AWS conforms to accessibility standards. AWS is committed to continually advancing the accessibility of our services and products from a customer perspective. If you happen to encounter any accessibility bugs, please report it to aws-accessibility@amazon.com.
