### ISSUE TITLE
Support for React 18

### ISSUE THREAD

**Issue by dave-moser** [aws/awsui-documentation#39]
**Describe the bug**
When deploying aws-ui/components-react to a React 18 application, dependencies cannot be resolved.  You are forced to use the --legacy-peer-deps flag with npm install.

React 18 is required for all new create-react-application installations.

**To Reproduce**
create a new React application with npx create-react-app
install the @aws-ui/components-react components
you will receive an error:

npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8 || ^17" from @awsui/components-react@3.0.483
npm ERR! node_modules/@awsui/components-react
npm ERR!   @awsui/components-react@"^3.0.483" from the root project

**Expected behavior**
You should be able to install the components.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [macOS]

**Comment by JakobBlomberg** [comment]
Hi, 
When can we expect aws-ui/components-react to work with React 18?

**Comment by gethinwebster** [comment]
We don't currently have an ETA for this. We are evaluating the potential problems/gaps, and once we are confident that we can safely support React 18 without issues we will update our package config accordingly.

**Comment by just-boris** [comment]
Starting from `@awsui/components-react@3.0.496` the react@18 was added to allowed peer deps range. Resolving
