### ISSUE TITLE
Select Form Items hidden within table

### ISSUE THREAD

**Issue by joshpetit** [aws/awsui-documentation#45]
**Describe the bug**
When you put a select form item within a table, the options are hidden.

**To Reproduce**
use this table:

```tsx
      <Table
        items={items.map((item, i) => {
          return { ...item, index: i };
        })}
        columnDefinitions={[
          {
            header: "Options",
            cell: (item) => {
              return (
                <Select
                  options={Object.keys(Options).map((str) => {
                    return {
                      value: str,
                      label: str,
                    };
                  })}
                  selectedOption={{value: item.option}}
                  onChange={(event) => {
                    const editedItem = items[item.index];
                    const newValue = {
                      ...editedItem,

                    };
                    const newItems = items.map((val, index) =>
                      index === item.index ? newValue : val
                    );
                    setItems(newItems);
                  }}
                />
```

**Expected behavior**
I would expect the drop down items not to be hidden, to show overtop the table elements

**Screenshots**
![image](https://user-images.githubusercontent.com/59021155/170097148-6fa2722e-b625-4591-9198-8fe9e23ace2c.png)

**Environment (please complete the following information):**
 - OS: macos
 - Browser Firefox
 - Version 100

**Additional context**
This is for for components-react v3.0.80

**Comment by rubencarvalho** [comment]
Hello,

Please consider using the `expandToViewport` property in the `Select` component. Enabling this property will allow the dropdown to extend beyond its parent by using fixed positioning and [React Portals](https://reactjs.org/docs/portals.html).

However, please consider other UX patterns, as it's generally not a recommended to have a `Select` embedded in a table cell.

Thank you!

**Comment by joshpetit** [comment]
Thanks!
