### ISSUE TITLE
How to catch the click event on Bar Chart(or Line Chart,Pie Chart)?

### ISSUE THREAD

**Issue by hejinzhi** [aws/awsui-documentation#47]
I want to get what bar I click on the Bar Chart,how to do it ,Thanks

**Comment by rubencarvalho** [comment]
Hello!

We currently don't offer any API for detecting a click on the Bar chart. The `onHighlightChange` event is the closest we currently support.

Could you tell us more about your use case? Why would you need this?

Thank you in advance.

**Comment by hejinzhi** [comment]
For example, bar chart show all the province ，when i click one bar，i want to show all the cityes under the province(Drill down). But now, I can not get what province i click. Is there any way to do that?Thank you

**Comment by timogasda** [comment]
Hello!

Unfortunately, this is currently not supported by the bar chart component.
The chart components are designed to visualize data. They are not meant to be used for navigation or drill-down.
