### ISSUE TITLE
can not set date picker control value with js

### ISSUE THREAD

**Issue by aqiao** [aws/awsui-documentation#48]
when i use the datepicker control,  i'd like to set the value with js dynamically, i tried 

```
let a = document.querySelector('awsui-date-picker').datepicker();
a.value = '2022-05-31';
```
but it shows datepicker() is not function.
please guide me how set datepicker control value with js, thanks in advance

**Comment by timogasda** [comment]
Hello!

Unfortunately, setting the value of our components using JavaScript is not supported. The components are React components first and foremost, and their state should therefore be controlled with React.

For example:

```jsx
function() {
  const [value, setValue] = React.useState('2022-05-31');

  return <DatePicker value={value} onChange={({ detail }) => setValue(detail.value)} />
}
```

**Comment by aqiao** [comment]
got it , thanks timogasda
