### ISSUE TITLE
Tree component

### ISSUE THREAD

**Issue by EliaContiniCL-CH** [aws/awsui-documentation#50]
Hi all,

for my project I need a tree component like the one used in [AWS Organizations - Accounts](https://console.aws.amazon.com/organizations/v2/home/accounts). Looking for it in the available components library I did not find nothing.

Is this component available with another name?
If not, do you have some suggestions about a tree component that can be easily integrated (styled like) as AWS UI Component?

Thank you for any information/suggestion.
Elia

**Comment by johannes-weber** [comment]
Hello Elia,
Thanks for opening this issue. The tree-like component you are referencing is not part of the [AWS UI Component library](https://github.com/aws/awsui-components-react).

You could create your custom component using the AWS UI Components. To get a sense about which components are used in the referenced example, you could inspect it in your dev tools.

Feel free to open another issue if you have any other questions about the AWS UI in general or any of its components.

**Comment by EliaContiniCL-CH** [comment]
Hi Johannes,

Thank you for the information and the tips.
